on: 
  workflow_dispatch:
    inputs:
      device:
        description: 'Select device'     
        required: true
        type: choice
        options:
        - AX1800
        - AXT1800
        - MT2500
        - MT3000
        - SF1200
        - SFT1200
      sourcecode:
        description: 'Source code URL'     
        required: true
      pkgname:
        description: 'Openwrt package name'  
        required: true
      email:
        description: 'Git accuont email address'  
        required: false
      password:
        description: 'Git account password'  
        required: false
        
jobs:
  setpackage:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: build ipk
      id: build
      env:
        SOURCECODEURL: ${{ github.event.inputs.sourcecode }}
        PKGNAME: ${{ github.event.inputs.pkgname }}
        BOARD: ${{ github.event.inputs.device }}
        EMAIL: ${{ github.event.inputs.email }}
        PASSWORD: ${{ github.event.inputs.password }}
      run: |
        cd $GITHUB_WORKSPACE
        chmod +x ./build.sh
        ./build.sh

    - uses: actions/upload-artifact@main
      with:
        name: ${{ github.event.inputs.pkgname }}_related_ipks
        path: |
          ./*ipk*

    - name: 生成固件Release标签
      id: tag
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()

    - name: 发布固件至Release
      uses: softprops/action-gh-release@v2
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: ${{ env.FIRMWARE }}/*
        name: ${{ env.IPK_NAME }}
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
